"""Initial schema Trace and Observation tables

Revision ID: 2ef79bc4acc7
Revises: 
Create Date: 2025-11-01 15:06:06.482475+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ef79bc4acc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_project_id'), 'traces', ['project_id'], unique=False)
    op.create_index('ix_traces_project_timestamp', 'traces', ['project_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_traces_session_id'), 'traces', ['session_id'], unique=False)
    op.create_index('ix_traces_session_timestamp', 'traces', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_traces_timestamp'), 'traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_traces_user_id'), 'traces', ['user_id'], unique=False)
    op.create_index('ix_traces_user_timestamp', 'traces', ['user_id', 'timestamp'], unique=False)
    op.create_table('observations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_observation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('SPAN', 'GENERATION', 'EVENT', 'TOOL', 'AGENT', name='observationtype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_parent_id', 'observations', ['parent_observation_id'], unique=False)
    op.create_index(op.f('ix_observations_trace_id'), 'observations', ['trace_id'], unique=False)
    op.create_index('ix_observations_trace_start_time', 'observations', ['trace_id', 'start_time'], unique=False)
    op.create_index('ix_observations_type_start_time', 'observations', ['type', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_type_start_time', table_name='observations')
    op.drop_index('ix_observations_trace_start_time', table_name='observations')
    op.drop_index(op.f('ix_observations_trace_id'), table_name='observations')
    op.drop_index('ix_observations_parent_id', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_traces_user_timestamp', table_name='traces')
    op.drop_index(op.f('ix_traces_user_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_timestamp'), table_name='traces')
    op.drop_index('ix_traces_session_timestamp', table_name='traces')
    op.drop_index(op.f('ix_traces_session_id'), table_name='traces')
    op.drop_index('ix_traces_project_timestamp', table_name='traces')
    op.drop_index(op.f('ix_traces_project_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
