"""Add project environments and config versioning

Revision ID: 130a927e2862
Revises: 1a2b3c4d5e6f
Create Date: 2025-11-02 17:01:44.016356+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '130a927e2862'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_version',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parent_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['config_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_version_created_at'), 'config_version', ['created_at'], unique=False)
    op.create_index(op.f('ix_config_version_project_id'), 'config_version', ['project_id'], unique=False)
    op.create_index(op.f('ix_config_version_record_id'), 'config_version', ['record_id'], unique=False)
    op.create_index(op.f('ix_config_version_table_name'), 'config_version', ['table_name'], unique=False)
    op.create_index(op.f('ix_config_version_version_number'), 'config_version', ['version_number'], unique=False)
    op.create_table('project_environment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('env_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('swisper_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'env_type', name='uq_project_env_type')
    )
    op.create_index(op.f('ix_project_environment_env_type'), 'project_environment', ['env_type'], unique=False)
    op.create_index(op.f('ix_project_environment_project_id'), 'project_environment', ['project_id'], unique=False)
    op.create_table('config_deployment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('deployed_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environment.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['config_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_deployment_deployed_at'), 'config_deployment', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_config_deployment_environment_id'), 'config_deployment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_config_deployment_version_id'), 'config_deployment', ['version_id'], unique=False)
    op.alter_column('model_pricing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('model_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    
    # Data migration: Migrate existing projects to 3 environments
    # BEFORE dropping swisper_url and swisper_api_key columns
    op.execute("""
        -- For each existing project, create 3 environments
        -- Dev and Staging point to mock SAP (for testing)
        -- Production keeps existing URL
        
        -- Development environment (points to mock SAP)
        INSERT INTO project_environment 
            (id, project_id, env_type, swisper_url, api_key, created_at, updated_at)
        SELECT 
            gen_random_uuid()::text,
            p.id,
            'dev',
            'http://backend:8000/api/v1/mock-swisper',
            'mock_dev_key',
            NOW(),
            NOW()
        FROM projects p
        WHERE p.deleted_at IS NULL;
        
        -- Staging environment (points to mock SAP)
        INSERT INTO project_environment 
            (id, project_id, env_type, swisper_url, api_key, created_at, updated_at)
        SELECT 
            gen_random_uuid()::text,
            p.id,
            'staging',
            'http://backend:8000/api/v1/mock-swisper',
            'mock_staging_key',
            NOW(),
            NOW()
        FROM projects p
        WHERE p.deleted_at IS NULL;
        
        -- Production environment (keeps existing URL)
        INSERT INTO project_environment 
            (id, project_id, env_type, swisper_url, api_key, created_at, updated_at)
        SELECT 
            gen_random_uuid()::text,
            p.id,
            'production',
            p.swisper_url,
            p.swisper_api_key,
            NOW(),
            NOW()
        FROM projects p
        WHERE p.deleted_at IS NULL;
    """)
    
    # Now safe to drop old columns (data migrated to project_environment)
    op.drop_column('projects', 'swisper_url')
    op.drop_column('projects', 'swisper_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('swisper_api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('swisper_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.alter_column('model_pricing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('model_pricing', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_config_deployment_version_id'), table_name='config_deployment')
    op.drop_index(op.f('ix_config_deployment_environment_id'), table_name='config_deployment')
    op.drop_index(op.f('ix_config_deployment_deployed_at'), table_name='config_deployment')
    op.drop_table('config_deployment')
    op.drop_index(op.f('ix_project_environment_project_id'), table_name='project_environment')
    op.drop_index(op.f('ix_project_environment_env_type'), table_name='project_environment')
    op.drop_table('project_environment')
    op.drop_index(op.f('ix_config_version_version_number'), table_name='config_version')
    op.drop_index(op.f('ix_config_version_table_name'), table_name='config_version')
    op.drop_index(op.f('ix_config_version_record_id'), table_name='config_version')
    op.drop_index(op.f('ix_config_version_project_id'), table_name='config_version')
    op.drop_index(op.f('ix_config_version_created_at'), table_name='config_version')
    op.drop_table('config_version')
    # ### end Alembic commands ###
