"""Add project foreign key to traces

Revision ID: 8b62cb96a693
Revises: 5aa929e5793b
Create Date: 2025-11-02 04:55:58.092361+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b62cb96a693'
down_revision: Union[str, None] = '5aa929e5793b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traces', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'traces', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traces', type_='foreignkey')
    op.alter_column('traces', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
